<html>
<head>
<title>patched_tests_setup.py</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #808080;}
.s1 { color: #a9b7c6;}
.s2 { color: #cc7832;}
.s3 { color: #6a8759;}
.s4 { color: #629755; font-style: italic;}
.s5 { color: #6897bb;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
patched_tests_setup.py</font>
</center></td></tr></table>
<pre><span class="s0"># pylint:disable=missing-docstring,invalid-name,too-many-lines</span>
<span class="s2">from </span><span class="s1">__future__ </span><span class="s2">import </span><span class="s1">print_function</span><span class="s2">, </span><span class="s1">absolute_import</span><span class="s2">, </span><span class="s1">division</span>

<span class="s2">import </span><span class="s1">collections</span>
<span class="s2">import </span><span class="s1">contextlib</span>
<span class="s2">import </span><span class="s1">functools</span>
<span class="s2">import </span><span class="s1">sys</span>
<span class="s2">import </span><span class="s1">os</span>
<span class="s0"># At least on 3.6+, importing platform</span>
<span class="s0"># imports subprocess, which imports selectors. That</span>
<span class="s0"># can expose issues with monkey patching. We don't need it</span>
<span class="s0"># though.</span>
<span class="s0"># import platform</span>
<span class="s2">import </span><span class="s1">re</span>

<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">RUNNING_ON_APPVEYOR </span><span class="s2">as </span><span class="s1">APPVEYOR</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">RUNNING_ON_TRAVIS </span><span class="s2">as </span><span class="s1">TRAVIS</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">RESOLVER_NOT_SYSTEM </span><span class="s2">as </span><span class="s1">ARES</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">RESOLVER_ARES</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">RESOLVER_DNSPYTHON</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">RUNNING_ON_CI</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">RUNNING_ON_MUSLLINUX</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">RUN_COVERAGE</span>


<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PYPY</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PYPY3</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY3</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY2</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY35</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY36</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY37</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY38</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY39</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY310</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">PY311</span>

<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">WIN</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">OSX</span>

<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">LIBUV</span>
<span class="s2">from </span><span class="s1">.sysinfo </span><span class="s2">import </span><span class="s1">CFFI_BACKEND</span>

<span class="s2">from </span><span class="s1">. </span><span class="s2">import </span><span class="s1">flaky</span>

<span class="s1">CPYTHON = </span><span class="s2">not </span><span class="s1">PYPY</span>

<span class="s0"># By default, test cases are expected to switch and emit warnings if there was none</span>
<span class="s0"># If a test is found in this list, it's expected not to switch.</span>
<span class="s1">no_switch_tests = </span><span class="s3">'''test_patched_select.SelectTestCase.test_error_conditions 
test_patched_ftplib.*.test_all_errors 
test_patched_ftplib.*.test_getwelcome 
test_patched_ftplib.*.test_sanitize 
test_patched_ftplib.*.test_set_pasv 
#test_patched_ftplib.TestIPv6Environment.test_af 
test_patched_socket.TestExceptions.testExceptionTree 
test_patched_socket.Urllib2FileobjectTest.testClose 
test_patched_socket.TestLinuxAbstractNamespace.testLinuxAbstractNamespace 
test_patched_socket.TestLinuxAbstractNamespace.testMaxName 
test_patched_socket.TestLinuxAbstractNamespace.testNameOverflow 
test_patched_socket.FileObjectInterruptedTestCase.* 
test_patched_urllib.* 
test_patched_asyncore.HelperFunctionTests.* 
test_patched_httplib.BasicTest.* 
test_patched_httplib.HTTPSTimeoutTest.test_attributes 
test_patched_httplib.HeaderTests.* 
test_patched_httplib.OfflineTest.* 
test_patched_httplib.HTTPSTimeoutTest.test_host_port 
test_patched_httplib.SourceAddressTest.testHTTPSConnectionSourceAddress 
test_patched_select.SelectTestCase.test_error_conditions 
test_patched_smtplib.NonConnectingTests.* 
test_patched_urllib2net.OtherNetworkTests.* 
test_patched_wsgiref.* 
test_patched_subprocess.HelperFunctionTests.* 
'''</span>

<span class="s1">ignore_switch_tests = </span><span class="s3">''' 
test_patched_socket.GeneralModuleTests.* 
test_patched_httpservers.BaseHTTPRequestHandlerTestCase.* 
test_patched_queue.* 
test_patched_signal.SiginterruptTest.* 
test_patched_urllib2.* 
test_patched_ssl.* 
test_patched_signal.BasicSignalTests.* 
test_patched_threading_local.* 
test_patched_threading.* 
'''</span>


<span class="s2">def </span><span class="s1">make_re(tests):</span>
    <span class="s1">tests = [x.strip().replace(</span><span class="s3">r'\.'</span><span class="s2">, </span><span class="s3">r'\\.'</span><span class="s1">).replace(</span><span class="s3">'*'</span><span class="s2">, </span><span class="s3">'.*?'</span><span class="s1">)</span>
             <span class="s2">for </span><span class="s1">x </span><span class="s2">in </span><span class="s1">tests.split(</span><span class="s3">'</span><span class="s2">\n</span><span class="s3">'</span><span class="s1">) </span><span class="s2">if </span><span class="s1">x.strip()]</span>
    <span class="s2">return </span><span class="s1">re.compile(</span><span class="s3">'^%s$' </span><span class="s1">% </span><span class="s3">'|'</span><span class="s1">.join(tests))</span>


<span class="s1">no_switch_tests = make_re(no_switch_tests)</span>
<span class="s1">ignore_switch_tests = make_re(ignore_switch_tests)</span>


<span class="s2">def </span><span class="s1">get_switch_expected(fullname):</span>
    <span class="s4">&quot;&quot;&quot; 
    &gt;&gt;&gt; get_switch_expected('test_patched_select.SelectTestCase.test_error_conditions') 
    False 
    &gt;&gt;&gt; get_switch_expected('test_patched_socket.GeneralModuleTests.testCrucialConstants') 
    False 
    &gt;&gt;&gt; get_switch_expected('test_patched_socket.SomeOtherTest.testHello') 
    True 
    &gt;&gt;&gt; get_switch_expected(&quot;test_patched_httplib.BasicTest.test_bad_status_repr&quot;) 
    False 
    &quot;&quot;&quot;</span>
    <span class="s0"># certain pylint versions mistype the globals as</span>
    <span class="s0"># str, not re.</span>
    <span class="s0"># pylint:disable=no-member</span>
    <span class="s2">if </span><span class="s1">ignore_switch_tests.match(fullname) </span><span class="s2">is not None</span><span class="s1">:</span>
        <span class="s2">return None</span>
    <span class="s2">if </span><span class="s1">no_switch_tests.match(fullname) </span><span class="s2">is not None</span><span class="s1">:</span>
        <span class="s2">return False</span>
    <span class="s2">return True</span>


<span class="s1">disabled_tests = [</span>
    <span class="s0"># XXX: While we debug latest updates. This is leaking</span>
    <span class="s3">'test_threading.ThreadTests.test_no_refcycle_through_target'</span><span class="s2">,</span>

    <span class="s0"># The server side takes awhile to shut down</span>
    <span class="s3">'test_httplib.HTTPSTest.test_local_bad_hostname'</span><span class="s2">,</span>
    <span class="s0"># These were previously 3.5+ issues (same as above)</span>
    <span class="s0"># but have been backported.</span>
    <span class="s3">'test_httplib.HTTPSTest.test_local_good_hostname'</span><span class="s2">,</span>
    <span class="s3">'test_httplib.HTTPSTest.test_local_unknown_cert'</span><span class="s2">,</span>


    <span class="s3">'test_threading.ThreadTests.test_PyThreadState_SetAsyncExc'</span><span class="s2">,</span>
    <span class="s0"># uses some internal C API of threads not available when threads are emulated with greenlets</span>

    <span class="s3">'test_threading.ThreadTests.test_join_nondaemon_on_shutdown'</span><span class="s2">,</span>
    <span class="s0"># asserts that repr(sleep) is '&lt;built-in function sleep&gt;'</span>

    <span class="s3">'test_urllib2net.TimeoutTest.test_ftp_no_timeout'</span><span class="s2">,</span>
    <span class="s3">'test_urllib2net.TimeoutTest.test_ftp_timeout'</span><span class="s2">,</span>
    <span class="s3">'test_urllib2net.TimeoutTest.test_http_no_timeout'</span><span class="s2">,</span>
    <span class="s3">'test_urllib2net.TimeoutTest.test_http_timeout'</span><span class="s2">,</span>
    <span class="s0"># accesses _sock.gettimeout() which is always in non-blocking mode</span>

    <span class="s3">'test_urllib2net.OtherNetworkTests.test_ftp'</span><span class="s2">,</span>
    <span class="s0"># too slow</span>

    <span class="s3">'test_urllib2net.OtherNetworkTests.test_urlwithfrag'</span><span class="s2">,</span>
    <span class="s0"># fails dues to some changes on python.org</span>

    <span class="s3">'test_urllib2net.OtherNetworkTests.test_sites_no_connection_close'</span><span class="s2">,</span>
    <span class="s0"># flaky</span>

    <span class="s3">'test_socket.UDPTimeoutTest.testUDPTimeout'</span><span class="s2">,</span>
    <span class="s0"># has a bug which makes it fail with error: (107, 'Transport endpoint is not connected')</span>
    <span class="s0"># (it creates a TCP socket, not UDP)</span>

    <span class="s3">'test_socket.GeneralModuleTests.testRefCountGetNameInfo'</span><span class="s2">,</span>
    <span class="s0"># fails with &quot;socket.getnameinfo loses a reference&quot; while the reference is only &quot;lost&quot;</span>
    <span class="s0"># because it is referenced by the traceback - any Python function would lose a reference like that.</span>
    <span class="s0"># the original getnameinfo does not &quot;lose&quot; it because it's in C.</span>

    <span class="s3">'test_socket.NetworkConnectionNoServer.test_create_connection_timeout'</span><span class="s2">,</span>
    <span class="s0"># replaces socket.socket with MockSocket and then calls create_connection.</span>
    <span class="s0"># this unfortunately does not work with monkey patching, because gevent.socket.create_connection</span>
    <span class="s0"># is bound to gevent.socket.socket and updating socket.socket does not affect it.</span>
    <span class="s0"># this issues also manifests itself when not monkey patching DNS: http://code.google.com/p/gevent/issues/detail?id=54</span>
    <span class="s0"># create_connection still uses gevent.socket.getaddrinfo while it should be using socket.getaddrinfo</span>

    <span class="s3">'test_asyncore.BaseTestAPI.test_handle_expt'</span><span class="s2">,</span>
    <span class="s0"># sends some OOB data and expect it to be detected as such; gevent.select.select does not support that</span>

    <span class="s0"># This one likes to check its own filename, but we rewrite</span>
    <span class="s0"># the file to a temp location during patching.</span>
    <span class="s3">'test_asyncore.HelperFunctionTests.test_compact_traceback'</span><span class="s2">,</span>

    <span class="s0"># expects time.sleep() to return prematurely in case of a signal;</span>
    <span class="s0"># gevent.sleep() is better than that and does not get interrupted</span>
    <span class="s0"># (unless signal handler raises an error)</span>
    <span class="s3">'test_signal.WakeupSignalTests.test_wakeup_fd_early'</span><span class="s2">,</span>

    <span class="s0"># expects select.select() to raise select.error(EINTR'interrupted</span>
    <span class="s0"># system call') gevent.select.select() does not get interrupted</span>
    <span class="s0"># (unless signal handler raises an error) maybe it should?</span>
    <span class="s3">'test_signal.WakeupSignalTests.test_wakeup_fd_during'</span><span class="s2">,</span>

    <span class="s0"># these rely on os.read raising EINTR which never happens with gevent.os.read</span>
    <span class="s3">'test_signal.SiginterruptTest.test_without_siginterrupt'</span><span class="s2">,</span>
    <span class="s3">'test_signal.SiginterruptTest.test_siginterrupt_on'</span><span class="s2">,</span>
    <span class="s3">'test_signal.SiginterruptTest.test_siginterrupt_off'</span><span class="s2">,</span>
    <span class="s0"># This one takes forever and relies on threading details</span>
    <span class="s3">'test_signal.StressTest.test_stress_modifying_handlers'</span><span class="s2">,</span>
    <span class="s0"># This uses an external file, and launches it. This means that it's not</span>
    <span class="s0"># actually testing gevent because there's no monkey-patch.</span>
    <span class="s3">'test_signal.PosixTests.test_interprocess_signal'</span><span class="s2">,</span>

    <span class="s3">'test_subprocess.ProcessTestCase.test_leak_fast_process_del_killed'</span><span class="s2">,</span>
    <span class="s3">'test_subprocess.ProcessTestCase.test_zombie_fast_process_del'</span><span class="s2">,</span>
    <span class="s0"># relies on subprocess._active which we don't use</span>

    <span class="s0"># Very slow, tries to open lots and lots of subprocess and files,</span>
    <span class="s0"># tends to timeout on CI.</span>
    <span class="s3">'test_subprocess.ProcessTestCase.test_no_leaking'</span><span class="s2">,</span>

    <span class="s0"># This test is also very slow, and has been timing out on Travis</span>
    <span class="s0"># since November of 2016 on Python 3, but now also seen on Python 2/Pypy.</span>
    <span class="s3">'test_subprocess.ProcessTestCase.test_leaking_fds_on_error'</span><span class="s2">,</span>

    <span class="s0"># Added between 3.6.0 and 3.6.3, uses _testcapi and internals</span>
    <span class="s0"># of the subprocess module. Backported to Python 2.7.16.</span>
    <span class="s3">'test_subprocess.POSIXProcessTestCase.test_stopped'</span><span class="s2">,</span>

    <span class="s3">'test_ssl.ThreadedTests.test_default_ciphers'</span><span class="s2">,</span>
    <span class="s3">'test_ssl.ThreadedTests.test_empty_cert'</span><span class="s2">,</span>
    <span class="s3">'test_ssl.ThreadedTests.test_malformed_cert'</span><span class="s2">,</span>
    <span class="s3">'test_ssl.ThreadedTests.test_malformed_key'</span><span class="s2">,</span>
    <span class="s3">'test_ssl.NetworkedTests.test_non_blocking_connect_ex'</span><span class="s2">,</span>
    <span class="s0"># XXX needs investigating</span>

    <span class="s3">'test_ssl.NetworkedTests.test_algorithms'</span><span class="s2">,</span>
    <span class="s0"># The host this wants to use, sha256.tbs-internet.com, is not resolvable</span>
    <span class="s0"># right now (2015-10-10), and we need to get Windows wheels</span>

    <span class="s0"># This started timing out randomly on Travis in oct/nov 2018. It appears</span>
    <span class="s0"># to be something with random number generation taking too long.</span>
    <span class="s3">'test_ssl.BasicSocketTests.test_random_fork'</span><span class="s2">,</span>

    <span class="s0"># Relies on the repr of objects (Py3)</span>
    <span class="s3">'test_ssl.BasicSocketTests.test_dealloc_warn'</span><span class="s2">,</span>

    <span class="s3">'test_urllib2.HandlerTests.test_cookie_redirect'</span><span class="s2">,</span>
    <span class="s0"># this uses cookielib which we don't care about</span>

    <span class="s3">'test_thread.ThreadRunningTests.test__count'</span><span class="s2">,</span>
    <span class="s3">'test_thread.TestForkInThread.test_forkinthread'</span><span class="s2">,</span>
    <span class="s0"># XXX needs investigating</span>

    <span class="s3">'test_subprocess.POSIXProcessTestCase.test_preexec_errpipe_does_not_double_close_pipes'</span><span class="s2">,</span>
    <span class="s0"># Does not exist in the test suite until 2.7.4+. Subclasses Popen, and overrides</span>
    <span class="s0"># _execute_child. But our version has a different parameter list than the</span>
    <span class="s0"># version that comes with PyPy/CPython, so fails with a TypeError.</span>

    <span class="s0"># This one crashes the interpreter if it has a bug parsing the</span>
    <span class="s0"># invalid data.</span>
    <span class="s3">'test_ssl.BasicSocketTests.test_parse_cert_CVE_2019_5010'</span><span class="s2">,</span>
    <span class="s0"># We had to copy in a newer version of the test file for SSL fixes</span>
    <span class="s0"># and this doesn't work reliably on all versions.</span>
    <span class="s3">'test_httplib.HeaderTests.test_headers_debuglevel'</span><span class="s2">,</span>

    <span class="s0"># On Appveyor with Python 3.8.0 and 3.7.5, this test</span>
    <span class="s0"># for __class_getitem__ fails. Presumably this was added</span>
    <span class="s0"># in a patch release (it's not in the PEP.) Sigh.</span>
    <span class="s0"># https://bugs.python.org/issue38979</span>
    <span class="s3">'test_context.ContextTest.test_contextvar_getitem'</span><span class="s2">,</span>
    <span class="s0"># The same patch that fixed that removed this test,</span>
    <span class="s0"># because it would now fail.</span>
    <span class="s3">'test_context.ContextTest.test_context_var_new_2'</span><span class="s2">,</span>
<span class="s1">]</span>


<span class="s2">if </span><span class="s1">sys.version_info[:</span><span class="s5">3</span><span class="s1">] &lt; (</span><span class="s5">2</span><span class="s2">, </span><span class="s5">7</span><span class="s2">, </span><span class="s5">18</span><span class="s1">):</span>
    <span class="s0"># The final release was 2.7.18. It added some new tests for new</span>
    <span class="s0"># fixes. At this writing, AppVeyor is still on 2.7.17.</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s3">'test_urllib2.MiscTests.test_url_host_with_control_char_rejected'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">OSX:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># These are timing dependent, and sometimes run into the OS X</span>
        <span class="s0"># kernel bug leading to 'Protocol wrong type for socket'.</span>
        <span class="s0"># See discussion at https://github.com/benoitc/gunicorn/issues/1487</span>
        <span class="s3">'test_ssl.SimpleBackgroundTests.test_connect_capath'</span><span class="s2">,</span>
        <span class="s3">'test_ssl.SimpleBackgroundTests.test_connect_with_context'</span><span class="s2">,</span>
    <span class="s1">]</span>
    <span class="s2">if </span><span class="s1">PYPY </span><span class="s2">and </span><span class="s1">PY2:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># This is broken in a standard download of PyPy.</span>
            <span class="s3">'test_subprocess.ProcessTestCase.test_executable_with_cwd'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PYPY </span><span class="s2">and </span><span class="s1">PY2 </span><span class="s2">and </span><span class="s1">WIN:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># XXX: New in PyPy 7.3.7. This times out. This is testing for</span>
        <span class="s0"># whether \0 in environment keys or values are excluded; they</span>
        <span class="s0"># are, before any waiting is done. The same goes for an '=' in</span>
        <span class="s0"># the key. It looks like we &quot;hang&quot; on the last clause that</span>
        <span class="s0"># tests when there is an '=' in the *value*. It's utterly</span>
        <span class="s0"># unclear to me why that causes an issue; we use the same</span>
        <span class="s0"># underlying CreateProcess call that PyPy itself does, and</span>
        <span class="s0"># no-where before that is the environment manipulated</span>
        <span class="s3">'test_subprocess.ProcesstestCase.test_invalid_env'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PYPY </span><span class="s2">and </span><span class="s1">PY37:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># The exact error message the code code checks for is different</span>
        <span class="s0"># (possibly just on macOS?). Plain PyPy3 fails as well.</span>
        <span class="s3">'test_signal.WakeupSignalTests.test_wakeup_write_error'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s3">'thread' </span><span class="s2">in </span><span class="s1">os.getenv(</span><span class="s3">'GEVENT_FILE'</span><span class="s2">, </span><span class="s3">''</span><span class="s1">):</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_double_close_on_error'</span>
        <span class="s0"># Fails with &quot;OSError: 9 invalid file descriptor&quot;; expect GC/lifetime issues</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY2 </span><span class="s2">and </span><span class="s1">PYPY:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># These appear to hang or take a long time for some reason?</span>
        <span class="s0"># Likely a hostname/binding issue or failure to properly close/gc sockets.</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_head_via_send_error'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_head_keep_alive'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_send_blank'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_send_error'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_command'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_handler'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.CGIHTTPServerTestcase.test_post'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.CGIHTTPServerTestCase.test_query_with_continuous_slashes'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.CGIHTTPServerTestCase.test_query_with_multiple_question_mark'</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.CGIHTTPServerTestCase.test_os_environ_is_not_altered'</span><span class="s2">,</span>

        <span class="s0"># This one sometimes results on connection refused</span>
        <span class="s3">'test_urllib2_localnet.TestUrlopen.test_info'</span><span class="s2">,</span>
        <span class="s0"># Sometimes hangs</span>
        <span class="s3">'test_ssl.ThreadedTests.test_socketserver'</span><span class="s2">,</span>
        <span class="s0"># We had to update 'CERTFILE' to continue working, but</span>
        <span class="s0"># this test hasn't been updated yet (the CPython tests</span>
        <span class="s0"># are also too new to run on PyPy).</span>
        <span class="s3">'test_ssl.BasicSocketTests.test_parse_cert'</span><span class="s2">,</span>

    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY2 </span><span class="s2">and </span><span class="s1">WIN:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This test randomly produces a 'LoopExit: Would block forever'</span>
        <span class="s0"># on 'self.serv.accept()', but only on Windows with Python 2. Possibly</span>
        <span class="s0"># due to the weird refcounting involving socket.makefile (just a guess)?</span>
        <span class="s0"># Seen in both PyPy 7.3 and CPython 2.7.x</span>
        <span class="s0"># https://ci.appveyor.com/project/denik/gevent/builds/36874106/job/guyq6h9k56n81uf6#L563</span>
        <span class="s3">'test_socket.BasicTCPTest2.testDup'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">LIBUV:</span>
    <span class="s0"># epoll appears to work with these just fine in some cases;</span>
    <span class="s0"># kqueue (at least on OS X, the only tested kqueue system)</span>
    <span class="s0"># never does (failing with abort())</span>
    <span class="s0"># (epoll on Raspbian 8.0/Debian Jessie/Linux 4.1.20 works;</span>
    <span class="s0"># on a VirtualBox image of Ubuntu 15.10/Linux 4.2.0 both tests fail;</span>
    <span class="s0"># Travis CI Ubuntu 12.04 precise/Linux 3.13 causes one of these tests to hang forever)</span>
    <span class="s0"># XXX: Retry this with libuv 1.12+</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># A 2.7 test. Tries to fork, and libuv cannot fork</span>
        <span class="s3">'test_signal.InterProcessSignalTests.test_main'</span><span class="s2">,</span>
        <span class="s0"># Likewise, a forking problem</span>
        <span class="s3">'test_signal.SiginterruptTest.test_siginterrupt_off'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">PY2:</span>

        <span class="s2">if </span><span class="s1">TRAVIS:</span>

            <span class="s2">if </span><span class="s1">CPYTHON:</span>

                <span class="s1">disabled_tests += [</span>
                    <span class="s0"># This appears to crash the process, for some reason,</span>
                    <span class="s0"># but only on CPython 2.7.14 on Travis. Cannot reproduce in</span>
                    <span class="s0"># 2.7.14 on macOS or 2.7.12 in local Ubuntu 16.04</span>
                    <span class="s3">'test_subprocess.POSIXProcessTestCase.test_close_fd_0'</span><span class="s2">,</span>
                    <span class="s3">'test_subprocess.POSIXProcessTestCase.test_close_fds_0_1'</span><span class="s2">,</span>
                    <span class="s3">'test_subprocess.POSIXProcessTestCase.test_close_fds_0_2'</span><span class="s2">,</span>
                <span class="s1">]</span>

            <span class="s2">if </span><span class="s1">PYPY:</span>
                <span class="s1">disabled_tests += [</span>
                    <span class="s0"># This seems to crash the interpreter. I cannot reproduce</span>
                    <span class="s0"># on macOS or local Linux VM.</span>
                    <span class="s0"># See https://travis-ci.org/gevent/gevent/jobs/348661604#L709</span>
                    <span class="s3">'test_smtplib.TooLongLineTests.testLineTooLong'</span><span class="s2">,</span>
                <span class="s1">]</span>
                <span class="s2">if </span><span class="s1">ARES:</span>

                    <span class="s1">disabled_tests += [</span>
                        <span class="s0"># This can timeout with a socket timeout in ssl.wrap_socket(c)</span>
                        <span class="s0"># on Travis. I can't reproduce locally.</span>
                        <span class="s3">'test_ssl.ThreadedTests.test_handshake_timeout'</span><span class="s2">,</span>
                    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">PY3:</span>

        <span class="s1">disabled_tests += [</span>
            <span class="s0"># This test wants to pass an arbitrary fileno</span>
            <span class="s0"># to a socket and do things with it. libuv doesn't like this,</span>
            <span class="s0"># it raises EPERM. It is disabled on windows already.</span>
            <span class="s0"># It depends on whether we had a fd already open and multiplexed with</span>
            <span class="s3">'test_socket.GeneralModuleTests.test_unknown_socket_family_repr'</span><span class="s2">,</span>
            <span class="s0"># And yes, there's a typo in some versions.</span>
            <span class="s3">'test_socket.GeneralModuleTests.test_uknown_socket_family_repr'</span><span class="s2">,</span>
        <span class="s1">]</span>

        <span class="s2">if </span><span class="s1">PY37:</span>

            <span class="s1">disabled_tests += [</span>
                <span class="s0"># This test sometimes fails at line 358. It's apparently</span>
                <span class="s0"># extremely sensitive to timing.</span>
                <span class="s3">'test_selectors.PollSelectorTestCase.test_timeout'</span><span class="s2">,</span>
            <span class="s1">]</span>

        <span class="s2">if </span><span class="s1">OSX:</span>
            <span class="s1">disabled_tests += [</span>
                <span class="s0"># XXX: Starting when we upgraded from libuv 1.18.0</span>
                <span class="s0"># to 1.19.2, this sometimes (usually) started having</span>
                <span class="s0"># a series of calls ('select.poll(0)', 'select.poll(-1)')</span>
                <span class="s0"># take longer than the allowed 0.5 seconds. Debugging showed that</span>
                <span class="s0"># it was the second call that took longer, for no apparent reason.</span>
                <span class="s0"># There doesn't seem to be a change in the source code to libuv that</span>
                <span class="s0"># would affect this.</span>
                <span class="s0"># XXX-XXX: This actually disables too many tests :(</span>
                <span class="s3">'test_selectors.PollSelectorTestCase.test_timeout'</span><span class="s2">,</span>
            <span class="s1">]</span>

        <span class="s2">if </span><span class="s1">RUN_COVERAGE:</span>

            <span class="s1">disabled_tests += [</span>
                <span class="s0"># Starting with #1145 this test (actually</span>
                <span class="s0"># TestTLS_FTPClassMixin) becomes sensitive to timings</span>
                <span class="s0"># under coverage.</span>
                <span class="s3">'test_ftplib.TestFTPClass.test_storlines'</span><span class="s2">,</span>
            <span class="s1">]</span>


    <span class="s2">if </span><span class="s1">sys.platform.startswith(</span><span class="s3">'linux'</span><span class="s1">):</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># crashes with EPERM, which aborts the epoll loop, even</span>
            <span class="s0"># though it was allowed in in the first place.</span>
            <span class="s3">'test_asyncore.FileWrapperTest.test_dispatcher'</span><span class="s2">,</span>
        <span class="s1">]</span>



    <span class="s2">if </span><span class="s1">WIN </span><span class="s2">and </span><span class="s1">PY2:</span>
        <span class="s0"># From PyPy2-v5.9.0 and CPython 2.7.14, using its version of tests,</span>
        <span class="s0"># which do work on darwin (and possibly linux?)</span>
        <span class="s0"># I can't produce them in a local VM running Windows 10</span>
        <span class="s0"># and the same pypy version.</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># These, which use asyncore, fail with</span>
            <span class="s0"># 'NoneType is not iterable' on 'conn, addr = self.accept()'</span>
            <span class="s0"># That returns None when the underlying socket raises</span>
            <span class="s0"># EWOULDBLOCK, which it will do because it's set to non-blocking</span>
            <span class="s0"># both by gevent and by libuv (at the level below python's knowledge)</span>
            <span class="s0"># I can *usually* reproduce these locally; it seems to be some sort</span>
            <span class="s0"># of race condition.</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_acct'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_all_errors'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_cwd'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_delete'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_dir'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_exceptions'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_getwelcome'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_line_too_long'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_login'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_makepasv'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_mkd'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_nlst'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_pwd'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_quit'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_makepasv'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_rename'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_retrbinary'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_retrbinary_rest'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_retrlines'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_retrlines_too_long'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_rmd'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_sanitize'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_set_pasv'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_size'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_storbinary'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_storbinary_rest'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_storlines'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_storlines_too_long'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_voidcmd'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClass.test_data_connection'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClass.test_control_connection'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClass.test_context'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClass.test_check_hostname'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClass.test_auth_ssl'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClass.test_auth_issued_twice'</span><span class="s2">,</span>

            <span class="s0"># This one times out, but it's still a non-blocking socket</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_makeport'</span><span class="s2">,</span>

            <span class="s0"># A timeout, possibly because of the way we handle interrupts?</span>
            <span class="s3">'test_socketserver.SocketServerTest.test_InterruptedServerSelectCall'</span><span class="s2">,</span>
            <span class="s3">'test_socketserver.SocketServerTest.test_InterruptServerSelectCall'</span><span class="s2">,</span>

            <span class="s0"># times out with something about threading?</span>
            <span class="s0"># The apparent hang is just after the print of &quot;waiting for server&quot;</span>
            <span class="s3">'test_socketserver.SocketServerTest.test_ThreadingTCPServer'</span><span class="s2">,</span>
            <span class="s3">'test_socketserver.SocketServerTest.test_ThreadingUDPServer'</span><span class="s2">,</span>
            <span class="s3">'test_socketserver.SocketServerTest.test_TCPServer'</span><span class="s2">,</span>
            <span class="s3">'test_socketserver.SocketServerTest.test_UDPServer'</span><span class="s2">,</span>

            <span class="s0"># This one might be like  'test_urllib2_localnet.TestUrlopen.test_https_with_cafile'?</span>
            <span class="s0"># XXX: Look at newer pypy and verify our usage of drop/reuse matches</span>
            <span class="s0"># theirs.</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_command'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_handler'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_head_keep_alive'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_head_via_send_error'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_header_close'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_internal_key_error'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_request_line_trimming'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_return_custom_status'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_send_blank'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_send_error'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_bogus'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_digits'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_invalid'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_none'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_get'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_head'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_invalid_requests'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_path_without_leading_slash'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.CGIHTTPServerTestCase.test_invaliduri'</span><span class="s2">,</span>
            <span class="s3">'test_httpservers.CGIHTTPServerTestCase.test_issue19435'</span><span class="s2">,</span>

            <span class="s0"># Unexpected timeouts sometimes</span>
            <span class="s3">'test_smtplib.TooLongLineTests.testLineTooLong'</span><span class="s2">,</span>
            <span class="s3">'test_smtplib.GeneralTests.testTimeoutValue'</span><span class="s2">,</span>

            <span class="s0"># This sometimes crashes, which can't be our fault?</span>
            <span class="s3">'test_ssl.BasicSocketTests.test_parse_cert_CVE_2019_5010'</span><span class="s2">,</span>

        <span class="s1">]</span>

        <span class="s2">if </span><span class="s1">PYPY:</span>
            <span class="s1">disabled_tests += [</span>
                <span class="s0"># appears to timeout?</span>
                <span class="s3">'test_threading.ThreadTests.test_finalize_with_trace'</span><span class="s2">,</span>
                <span class="s3">'test_asyncore.DispatcherWithSendTests_UsePoll.test_send'</span><span class="s2">,</span>
                <span class="s3">'test_asyncore.DispatcherWithSendTests.test_send'</span><span class="s2">,</span>

                <span class="s0"># More unexpected timeouts</span>
                <span class="s3">'test_ssl.ContextTests.test__https_verify_envvar'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_check_output'</span><span class="s2">,</span>
                <span class="s3">'test_telnetlib.ReadTests.test_read_eager_A'</span><span class="s2">,</span>

                <span class="s0"># But on Windows, our gc fix for that doesn't work anyway</span>
                <span class="s0"># so we have to disable it.</span>
                <span class="s3">'test_urllib2_localnet.TestUrlopen.test_https_with_cafile'</span><span class="s2">,</span>

                <span class="s0"># These tests hang. see above.</span>
                <span class="s3">'test_threading.ThreadJoinOnShutdown.test_1_join_on_shutdown'</span><span class="s2">,</span>
                <span class="s3">'test_threading.ThreadingExceptionTests.test_print_exception'</span><span class="s2">,</span>

                <span class="s0"># Our copy of these in test__subprocess.py also hangs.</span>
                <span class="s0"># Anything that uses Popen.communicate or directly uses</span>
                <span class="s0"># Popen.stdXXX.read hangs. It's not clear why.</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_communicate'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_cwd'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_env'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_stderr_pipe'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_stdout_pipe'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_stdout_stderr_pipe'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_stderr_redirect_with_no_stdout_redirect'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_stdout_filedes_of_stdout'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestcase.test_stdout_none'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestcase.test_universal_newlines'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.ProcessTestcase.test_writes_before_communicate'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.Win32ProcessTestCase._kill_process'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.Win32ProcessTestCase._kill_dead_process'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.Win32ProcessTestCase.test_shell_sequence'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.Win32ProcessTestCase.test_shell_string'</span><span class="s2">,</span>
                <span class="s3">'test_subprocess.CommandsWithSpaces.with_spaces'</span><span class="s2">,</span>
            <span class="s1">]</span>


    <span class="s2">if </span><span class="s1">WIN:</span>

        <span class="s1">disabled_tests += [</span>
            <span class="s0"># This test winds up hanging a long time.</span>
            <span class="s0"># Inserting GCs doesn't fix it.</span>
            <span class="s3">'test_ssl.ThreadedTests.test_handshake_timeout'</span><span class="s2">,</span>

            <span class="s0"># These sometimes raise LoopExit, for no apparent reason,</span>
            <span class="s0"># mostly but not exclusively on Python 2. Sometimes (often?)</span>
            <span class="s0"># this happens in the setUp() method when we attempt to get a client</span>
            <span class="s0"># connection</span>
            <span class="s3">'test_socket.BufferIOTest.testRecvFromIntoBytearray'</span><span class="s2">,</span>
            <span class="s3">'test_socket.BufferIOTest.testRecvFromIntoArray'</span><span class="s2">,</span>
            <span class="s3">'test_socket.BufferIOTest.testRecvIntoArray'</span><span class="s2">,</span>
            <span class="s3">'test_socket.BufferIOTest.testRecvIntoMemoryview'</span><span class="s2">,</span>
            <span class="s3">'test_socket.BufferIOTest.testRecvFromIntoEmptyBuffer'</span><span class="s2">,</span>
            <span class="s3">'test_socket.BufferIOTest.testRecvFromIntoMemoryview'</span><span class="s2">,</span>
            <span class="s3">'test_socket.BufferIOTest.testRecvFromIntoSmallBuffer'</span><span class="s2">,</span>
            <span class="s3">'test_socket.BufferIOTest.testRecvIntoBytearray'</span><span class="s2">,</span>
        <span class="s1">]</span>

        <span class="s2">if </span><span class="s1">PY3:</span>

            <span class="s1">disabled_tests += [</span>
            <span class="s1">]</span>

            <span class="s2">if </span><span class="s1">APPVEYOR:</span>

                <span class="s1">disabled_tests += [</span>
                <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">PYPY:</span>

        <span class="s2">if </span><span class="s1">TRAVIS:</span>

            <span class="s1">disabled_tests += [</span>
                <span class="s0"># This sometimes causes a segfault for no apparent reason.</span>
                <span class="s0"># See https://travis-ci.org/gevent/gevent/jobs/327328704</span>
                <span class="s0"># Can't reproduce locally.</span>
                <span class="s3">'test_subprocess.ProcessTestCase.test_universal_newlines_communicate'</span><span class="s2">,</span>
            <span class="s1">]</span>

<span class="s2">if </span><span class="s1">RUN_COVERAGE </span><span class="s2">and </span><span class="s1">CFFI_BACKEND:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This test hangs in this combo for some reason</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_sendall_interrupted'</span><span class="s2">,</span>
        <span class="s0"># This can get a timeout exception instead of the Alarm</span>
        <span class="s3">'test_socket.TCPTimeoutTest.testInterruptedTimeout'</span><span class="s2">,</span>

        <span class="s0"># This test sometimes gets the wrong answer (due to changed timing?)</span>
        <span class="s3">'test_socketserver.SocketServerTest.test_ForkingUDPServer'</span><span class="s2">,</span>

        <span class="s0"># Timing and signals are off, so a handler exception doesn't get raised.</span>
        <span class="s0"># Seen under libev</span>
        <span class="s3">'test_signal.InterProcessSignalTests.test_main'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY2:</span>
    <span class="s2">if </span><span class="s1">TRAVIS:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># When we moved to group:travis_latest and dist:xenial,</span>
            <span class="s0"># this started returning a value (33554432L) != 0; presumably</span>
            <span class="s0"># because of updated SSL library? Only on CPython.</span>
            <span class="s3">'test_ssl.ContextTests.test_options'</span><span class="s2">,</span>
            <span class="s0"># When we moved to group:travis_latest and dist:xenial,</span>
            <span class="s0"># one of the values used started *working* when it was expected to fail.</span>
            <span class="s0"># The list of values and systems is long and complex, so</span>
            <span class="s0"># presumably something needs to be updated. Only on PyPy.</span>
            <span class="s3">'test_ssl.ThreadedTests.test_alpn_protocols'</span><span class="s2">,</span>
        <span class="s1">]</span>

    <span class="s1">disabled_tests += [</span>
        <span class="s0"># At least on OSX, this results in connection refused</span>
        <span class="s3">'test_urllib2_localnet.TestUrlopen.test_https_sni'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">sys.version_info[:</span><span class="s5">3</span><span class="s1">] &lt; (</span><span class="s5">2</span><span class="s2">, </span><span class="s5">7</span><span class="s2">, </span><span class="s5">16</span><span class="s1">):</span>
        <span class="s0"># We have 2.7.16 tests; older versions can fail</span>
        <span class="s0"># to validate some SSL things or are missing important support functions</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># Support functions</span>
            <span class="s3">'test_thread.ThreadRunningTests.test_nt_and_posix_stack_size'</span><span class="s2">,</span>
            <span class="s3">'test_thread.ThreadRunningTests.test_save_exception_state_on_error'</span><span class="s2">,</span>
            <span class="s3">'test_thread.ThreadRunningTests.test_starting_threads'</span><span class="s2">,</span>
            <span class="s3">'test_thread.BarrierTest.test_barrier'</span><span class="s2">,</span>
            <span class="s0"># Broken SSL</span>
            <span class="s3">'test_urllib2_localnet.TestUrlopen.test_https'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test__create_stdlib_context'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test_create_default_context'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test_options'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PYPY </span><span class="s2">and </span><span class="s1">sys.pypy_version_info[:</span><span class="s5">2</span><span class="s1">] == (</span><span class="s5">7</span><span class="s2">, </span><span class="s5">3</span><span class="s1">): </span><span class="s0"># pylint:disable=no-member</span>

    <span class="s2">if </span><span class="s1">OSX:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># This is expected to produce an SSLError, but instead it appears to</span>
            <span class="s0"># actually work. See above for when it started failing the same on</span>
            <span class="s0"># Travis.</span>
            <span class="s3">'test_ssl.ThreadedTests.test_alpn_protocols'</span><span class="s2">,</span>
            <span class="s0"># This fails, presumably due to the OpenSSL it's compiled with.</span>
            <span class="s3">'test_ssl.ThreadedTests.test_default_ecdh_curve'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PYPY3 </span><span class="s2">and </span><span class="s1">TRAVIS:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># If socket.SOCK_CLOEXEC is defined, this creates a socket</span>
        <span class="s0"># and tests its type with ``sock.type &amp; socket.SOCK_CLOEXEC``</span>
        <span class="s0"># We have a ``@property`` for ``type`` that takes care of</span>
        <span class="s0"># ``SOCK_NONBLOCK`` on Linux, but otherwise it's just a pass-through.</span>
        <span class="s0"># This started failing with PyPy 7.3.1 and it's not clear why.</span>
        <span class="s3">'test_socket.InheritanceTest.test_SOCK_CLOEXEC'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PYPY3 </span><span class="s2">and </span><span class="s1">WIN:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># test_httpservers.CGIHTTPServerTestCase all seem to hang.</span>
        <span class="s0"># There seem to be some general subprocess issues. This is</span>
        <span class="s0"># ignored entirely from known_failures.py</span>

        <span class="s0"># This produces:</span>
        <span class="s0">#</span>
        <span class="s0">#  OSError: [Errno 10014] The system detected an invalid</span>
        <span class="s0">#  pointer address in attempting to use a pointer argument in</span>
        <span class="s0">#  a call</span>
        <span class="s0">#</span>
        <span class="s0"># When calling socket.socket(fileno=fd) when we actually</span>
        <span class="s0"># call ``self._socket =self._gevent_sock_class()``.</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_socket_fileno'</span><span class="s2">,</span>

        <span class="s0"># This doesn't respect the scope properly</span>
        <span class="s0">#</span>
        <span class="s0">#  self.assertEqual(sockaddr, ('ff02::1de:c0:face:8d', 1234, 0, ifindex))</span>
        <span class="s0">#   AssertionError: Tuples differ: ('ff02::1de:c0:face:8d%42', 1234, 0, 42) != ('ff02::1de:c0:face:8d', 1234, 0, 42</span>
        <span class="s0">#</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_getaddrinfo_ipv6_scopeid_numeric'</span><span class="s2">,</span>

        <span class="s0"># self.assertEqual(newsock.get_inheritable(), False)</span>
        <span class="s0">#  AssertionError: True != False</span>
        <span class="s3">'test_socket.InheritanceTest.test_dup'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">def </span><span class="s1">_make_run_with_original(mod_name</span><span class="s2">, </span><span class="s1">func_name):</span>
    <span class="s1">@contextlib.contextmanager</span>
    <span class="s2">def </span><span class="s1">with_orig():</span>
        <span class="s1">mod = __import__(mod_name)</span>
        <span class="s1">now = getattr(mod</span><span class="s2">, </span><span class="s1">func_name)</span>
        <span class="s2">from </span><span class="s1">gevent.monkey </span><span class="s2">import </span><span class="s1">get_original</span>
        <span class="s1">orig = get_original(mod_name</span><span class="s2">, </span><span class="s1">func_name)</span>
        <span class="s2">try</span><span class="s1">:</span>
            <span class="s1">setattr(mod</span><span class="s2">, </span><span class="s1">func_name</span><span class="s2">, </span><span class="s1">orig)</span>
            <span class="s2">yield</span>
        <span class="s2">finally</span><span class="s1">:</span>
            <span class="s1">setattr(mod</span><span class="s2">, </span><span class="s1">func_name</span><span class="s2">, </span><span class="s1">now)</span>
    <span class="s2">return </span><span class="s1">with_orig</span>

<span class="s1">@contextlib.contextmanager</span>
<span class="s2">def </span><span class="s1">_gc_at_end():</span>
    <span class="s2">try</span><span class="s1">:</span>
        <span class="s2">yield</span>
    <span class="s2">finally</span><span class="s1">:</span>
        <span class="s2">import </span><span class="s1">gc</span>
        <span class="s1">gc.collect()</span>
        <span class="s1">gc.collect()</span>

<span class="s1">@contextlib.contextmanager</span>
<span class="s2">def </span><span class="s1">_flaky_socket_timeout():</span>
    <span class="s2">import </span><span class="s1">socket</span>
    <span class="s2">try</span><span class="s1">:</span>
        <span class="s2">yield</span>
    <span class="s2">except </span><span class="s1">socket.timeout:</span>
        <span class="s1">flaky.reraiseFlakyTestTimeout()</span>

<span class="s0"># Map from FQN to a context manager that will be wrapped around</span>
<span class="s0"># that test.</span>
<span class="s1">wrapped_tests = {</span>
<span class="s1">}</span>



<span class="s2">class </span><span class="s1">_PatchedTest(object):</span>
    <span class="s2">def </span><span class="s1">__init__(self</span><span class="s2">, </span><span class="s1">test_fqn):</span>
        <span class="s1">self._patcher = wrapped_tests[test_fqn]</span>

    <span class="s2">def </span><span class="s1">__call__(self</span><span class="s2">, </span><span class="s1">orig_test_fn):</span>

        <span class="s1">@functools.wraps(orig_test_fn)</span>
        <span class="s2">def </span><span class="s1">test(*args</span><span class="s2">, </span><span class="s1">**kwargs):</span>
            <span class="s2">with </span><span class="s1">self._patcher():</span>
                <span class="s2">return </span><span class="s1">orig_test_fn(*args</span><span class="s2">, </span><span class="s1">**kwargs)</span>
        <span class="s2">return </span><span class="s1">test</span>



<span class="s2">if </span><span class="s1">sys.version_info[:</span><span class="s5">3</span><span class="s1">] &lt;= (</span><span class="s5">2</span><span class="s2">, </span><span class="s5">7</span><span class="s2">, </span><span class="s5">11</span><span class="s1">):</span>

    <span class="s1">disabled_tests += [</span>
        <span class="s0"># These were added/fixed in 2.7.12+</span>
        <span class="s3">'test_ssl.ThreadedTests.test__https_verify_certificates'</span><span class="s2">,</span>
        <span class="s3">'test_ssl.ThreadedTests.test__https_verify_envvar'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">OSX:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_run_abort'</span><span class="s2">,</span>
        <span class="s0"># causes Mac OS X to show &quot;Python crashes&quot; dialog box which is annoying</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">WIN:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># Issue with Unix vs DOS newlines in the file vs from the server</span>
        <span class="s3">'test_ssl.ThreadedTests.test_socketserver'</span><span class="s2">,</span>
        <span class="s0"># This sometimes hangs (only on appveyor)</span>
        <span class="s3">'test_ssl.ThreadedTests.test_asyncore_server'</span><span class="s2">,</span>
        <span class="s0"># On appveyor, this sometimes produces 'A non-blocking socket</span>
        <span class="s0"># operation could not be completed immediately', followed by</span>
        <span class="s0"># 'No connection could be made because the target machine</span>
        <span class="s0"># actively refused it'</span>
        <span class="s3">'test_socket.NonBlockingTCPTests.testAccept'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s0"># These are a problem on 3.5; on 3.6+ they wind up getting (accidentally) disabled.</span>
    <span class="s1">wrapped_tests.update({</span>
        <span class="s3">'test_socket.SendfileUsingSendTest.testWithTimeout'</span><span class="s1">: _flaky_socket_timeout</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendTest.testOffset'</span><span class="s1">: _flaky_socket_timeout</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendTest.testRegularFile'</span><span class="s1">: _flaky_socket_timeout</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendTest.testCount'</span><span class="s1">: _flaky_socket_timeout</span><span class="s2">,</span>
    <span class="s1">})</span>

<span class="s2">if </span><span class="s1">PYPY:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># Does not exist in the CPython test suite, tests for a specific bug</span>
        <span class="s0"># in PyPy's forking. Only runs on linux and is specific to the PyPy</span>
        <span class="s0"># implementation of subprocess (possibly explains the extra parameter to</span>
        <span class="s0"># _execut_child)</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_failed_child_execute_fd_leak'</span><span class="s2">,</span>
        <span class="s0"># On some platforms, this returns &quot;zlib_compression&quot;, but the test is looking for</span>
        <span class="s0"># &quot;ZLIB&quot;</span>
        <span class="s3">'test_ssl.ThreadedTests.test_compression'</span><span class="s2">,</span>

        <span class="s0"># These are flaxy, apparently a race condition? Began with PyPy 2.7-7 and 3.6-7</span>
        <span class="s3">'test_asyncore.TestAPI_UsePoll.test_handle_error'</span><span class="s2">,</span>
        <span class="s3">'test_asyncore.TestAPI_UsePoll.test_handle_read'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">WIN:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># Starting in 7.3.1 on Windows, this stopped raising ValueError; it appears to</span>
            <span class="s0"># be a bug in PyPy.</span>
            <span class="s3">'test_signal.WakeupFDTests.test_invalid_fd'</span><span class="s2">,</span>
            <span class="s0"># Likewise for 7.3.1. See the comments for PY35</span>
            <span class="s3">'test_socket.GeneralModuleTests.test_sock_ioctl'</span><span class="s2">,</span>
        <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">PY36:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># These are flaky, beginning in 3.6-alpha 7.0, not finding some flag</span>
            <span class="s0"># set, apparently a race condition</span>
            <span class="s3">'test_asyncore.TestAPI_UveIPv6Poll.test_handle_accept'</span><span class="s2">,</span>
            <span class="s3">'test_asyncore.TestAPI_UveIPv6Poll.test_handle_accepted'</span><span class="s2">,</span>
            <span class="s3">'test_asyncore.TestAPI_UveIPv6Poll.test_handle_close'</span><span class="s2">,</span>
            <span class="s3">'test_asyncore.TestAPI_UveIPv6Poll.test_handle_write'</span><span class="s2">,</span>

            <span class="s3">'test_asyncore.TestAPI_UseIPV6Select.test_handle_read'</span><span class="s2">,</span>

            <span class="s0"># These are reporting 'ssl has no attribute ...'</span>
            <span class="s0"># This could just be an OSX thing</span>
            <span class="s3">'test_ssl.ContextTests.test__create_stdlib_context'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test_create_default_context'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test_get_ciphers'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test_options'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test_constants'</span><span class="s2">,</span>

            <span class="s0"># These tend to hang for some reason, probably not properly</span>
            <span class="s0"># closed sockets.</span>
            <span class="s3">'test_socketserver.SocketServerTest.test_write'</span><span class="s2">,</span>

            <span class="s0"># This uses ctypes to do funky things including using ptrace,</span>
            <span class="s0"># it hangs</span>
            <span class="s3">'test_subprocess.ProcessTestcase.test_child_terminated_in_stopped_state'</span><span class="s2">,</span>

            <span class="s0"># Certificate errors; need updated test</span>
            <span class="s3">'test_urllib2_localnet.TestUrlopen.test_https'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s0"># Generic Python 3</span>

<span class="s2">if </span><span class="s1">PY3:</span>

    <span class="s1">disabled_tests += [</span>
        <span class="s0"># Triggers the crash reporter</span>
        <span class="s3">'test_threading.SubinterpThreadingTests.test_daemon_threads_fatal_error'</span><span class="s2">,</span>

        <span class="s0"># Relies on an implementation detail, Thread._tstate_lock</span>
        <span class="s3">'test_threading.ThreadTests.test_tstate_lock'</span><span class="s2">,</span>
        <span class="s0"># Relies on an implementation detail (reprs); we have our own version</span>
        <span class="s3">'test_threading.ThreadTests.test_various_ops'</span><span class="s2">,</span>
        <span class="s3">'test_threading.ThreadTests.test_various_ops_large_stack'</span><span class="s2">,</span>
        <span class="s3">'test_threading.ThreadTests.test_various_ops_small_stack'</span><span class="s2">,</span>

        <span class="s0"># Relies on Event having a _cond and an _reset_internal_locks()</span>
        <span class="s0"># XXX: These are commented out in the source code of test_threading because</span>
        <span class="s0"># this doesn't work.</span>
        <span class="s0"># 'lock_tests.EventTests.test_reset_internal_locks',</span>

        <span class="s0"># Python bug 13502. We may or may not suffer from this as its</span>
        <span class="s0"># basically a timing race condition.</span>
        <span class="s0"># XXX Same as above</span>
        <span class="s0"># 'lock_tests.EventTests.test_set_and_clear',</span>

        <span class="s0"># These tests want to assert on the type of the class that implements</span>
        <span class="s0"># `Popen.stdin`; we use a FileObject, but they expect different subclasses</span>
        <span class="s0"># from the `io` module</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_io_buffered_by_default'</span><span class="s2">,</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_io_unbuffered_works'</span><span class="s2">,</span>

        <span class="s0"># 3.3 exposed the `endtime` argument to wait accidentally.</span>
        <span class="s0"># It is documented as deprecated and not to be used since 3.4</span>
        <span class="s0"># This test in 3.6.3 wants to use it though, and we don't have it.</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_wait_endtime'</span><span class="s2">,</span>

        <span class="s0"># These all want to inspect the string value of an exception raised</span>
        <span class="s0"># by the exec() call in the child. The _posixsubprocess module arranges</span>
        <span class="s0"># for better exception handling and printing than we do.</span>
        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_exception_bad_args_0'</span><span class="s2">,</span>
        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_exception_bad_executable'</span><span class="s2">,</span>
        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_exception_cwd'</span><span class="s2">,</span>
        <span class="s0"># Relies on a 'fork_exec' attribute that we don't provide</span>
        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_exception_errpipe_bad_data'</span><span class="s2">,</span>
        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_exception_errpipe_normal'</span><span class="s2">,</span>

        <span class="s0"># Python 3 fixed a bug if the stdio file descriptors were closed;</span>
        <span class="s0"># we still have that bug</span>
        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_small_errpipe_write_fd'</span><span class="s2">,</span>

        <span class="s0"># Relies on implementation details (some of these tests were added in 3.4,</span>
        <span class="s0"># but PyPy3 is also shipping them.)</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_SocketType_is_socketobject'</span><span class="s2">,</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_dealloc_warn'</span><span class="s2">,</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_repr'</span><span class="s2">,</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_str_for_enums'</span><span class="s2">,</span>
        <span class="s3">'test_socket.GeneralModuleTests.testGetaddrinfo'</span><span class="s2">,</span>

    <span class="s1">]</span>
    <span class="s2">if </span><span class="s1">TRAVIS:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># test_cwd_with_relative_executable tends to fail</span>
            <span class="s0"># on Travis...it looks like the test processes are stepping</span>
            <span class="s0"># on each other and messing up their temp directories. We tend to get things like</span>
            <span class="s0">#    saved_dir = os.getcwd()</span>
            <span class="s0">#   FileNotFoundError: [Errno 2] No such file or directory</span>
            <span class="s3">'test_subprocess.ProcessTestCase.test_cwd_with_relative_arg'</span><span class="s2">,</span>
            <span class="s3">'test_subprocess.ProcessTestCaseNoPoll.test_cwd_with_relative_arg'</span><span class="s2">,</span>
            <span class="s3">'test_subprocess.ProcessTestCase.test_cwd_with_relative_executable'</span><span class="s2">,</span>

            <span class="s0"># In 3.7 and 3.8 on Travis CI, this appears to take the full 3 seconds.</span>
            <span class="s0"># Can't reproduce it locally. We have our own copy of this that takes</span>
            <span class="s0"># timing on CI into account.</span>
            <span class="s3">'test_subprocess.RunFuncTestCase.test_run_with_shell_timeout_and_capture_output'</span><span class="s2">,</span>
        <span class="s1">]</span>

    <span class="s1">disabled_tests += [</span>
        <span class="s0"># XXX: BUG: We simply don't handle this correctly. On CPython,</span>
        <span class="s0"># we wind up raising a BlockingIOError and then</span>
        <span class="s0"># BrokenPipeError and then some random TypeErrors, all on the</span>
        <span class="s0"># server. CPython 3.5 goes directly to socket.send() (via</span>
        <span class="s0"># socket.makefile), whereas CPython 3.6 uses socket.sendall().</span>
        <span class="s0"># On PyPy, the behaviour is much worse: we hang indefinitely, perhaps exposing a problem</span>
        <span class="s0"># with our signal handling.</span>

        <span class="s0"># In actuality, though, this test doesn't fully test the EINTR it expects</span>
        <span class="s0"># to under gevent (because if its EWOULDBLOCK retry behaviour.)</span>
        <span class="s0"># Instead, the failures were all due to `pthread_kill` trying to send a signal</span>
        <span class="s0"># to a greenlet instead of a real thread. The solution is to deliver the signal</span>
        <span class="s0"># to the real thread by letting it get the correct ID, and we previously</span>
        <span class="s0"># used make_run_with_original to make it do that.</span>
        <span class="s0">#</span>
        <span class="s0"># But now that we have disabled our wrappers around Thread.join() in favor</span>
        <span class="s0"># of the original implementation, that causes problems:</span>
        <span class="s0"># background.join() thinks that it is the current thread, and won't let it</span>
        <span class="s0"># be joined.</span>
        <span class="s3">'test_wsgiref.IntegrationTests.test_interrupted_write'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s0"># PyPy3 3.5.5 v5.8-beta</span>

<span class="s2">if </span><span class="s1">PYPY3:</span>


    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This raises 'RuntimeError: reentrant call' when exiting the</span>
        <span class="s0"># process tries to close the stdout stream; no other platform does this.</span>
        <span class="s0"># Seen in both 3.3 and 3.5 (5.7 and 5.8)</span>
        <span class="s3">'test_signal.SiginterruptTest.test_siginterrupt_off'</span><span class="s2">,</span>
    <span class="s1">]</span>


<span class="s2">if </span><span class="s1">PYPY </span><span class="s2">and </span><span class="s1">PY3:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This fails to close all the FDs, at least on CI. On OS X, many of the</span>
        <span class="s0"># POSIXProcessTestCase fd tests have issues.</span>
        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_close_fds_when_max_fd_is_lowered'</span><span class="s2">,</span>

        <span class="s0"># This has the wrong constants in 5.8 (but worked in 5.7), at least on</span>
        <span class="s0"># OS X. It finds &quot;zlib compression&quot; but expects &quot;ZLIB&quot;.</span>
        <span class="s3">'test_ssl.ThreadedTests.test_compression'</span><span class="s2">,</span>

        <span class="s0"># The below are new with 5.10.1</span>
        <span class="s0"># This gets an EOF in violation of protocol; again, even without gevent</span>
        <span class="s0"># (at least on OS X; it's less consistent about that on travis)</span>
        <span class="s3">'test_ssl.NetworkedBIOTests.test_handshake'</span><span class="s2">,</span>

        <span class="s0"># This passes various &quot;invalid&quot; strings and expects a ValueError. not sure why</span>
        <span class="s0"># we don't see errors on CPython.</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_invalid_env'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">OSX:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># These all fail with &quot;invalid_literal for int() with base 10: b''&quot;</span>
            <span class="s3">'test_subprocess.POSIXProcessTestCase.test_close_fds'</span><span class="s2">,</span>
            <span class="s3">'test_subprocess.POSIXProcessTestCase.test_close_fds_after_preexec'</span><span class="s2">,</span>
            <span class="s3">'test_subprocess.POSIXProcessTestCase.test_pass_fds'</span><span class="s2">,</span>
            <span class="s3">'test_subprocess.POSIXProcessTestCase.test_pass_fds_inheritable'</span><span class="s2">,</span>
            <span class="s3">'test_subprocess.POSIXProcessTestCase.test_pipe_cloexec'</span><span class="s2">,</span>


            <span class="s0"># The below are new with 5.10.1</span>
            <span class="s0"># These fail with 'OSError: received malformed or improperly truncated ancillary data'</span>
            <span class="s3">'test_socket.RecvmsgSCMRightsStreamTest.testCmsgTruncLen0'</span><span class="s2">,</span>
            <span class="s3">'test_socket.RecvmsgSCMRightsStreamTest.testCmsgTruncLen0Plus1'</span><span class="s2">,</span>
            <span class="s3">'test_socket.RecvmsgSCMRightsStreamTest.testCmsgTruncLen1'</span><span class="s2">,</span>
            <span class="s3">'test_socket.RecvmsgSCMRightsStreamTest.testCmsgTruncLen2Minus1'</span><span class="s2">,</span>

            <span class="s0"># Using the provided High Sierra binary, these fail with</span>
            <span class="s0"># 'ValueError: invalid protocol version _SSLMethod.PROTOCOL_SSLv3'.</span>
            <span class="s0"># gevent code isn't involved and running them unpatched has the same issue.</span>
            <span class="s3">'test_ssl.ContextTests.test_constructor'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test_protocol'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ContextTests.test_session_stats'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ThreadedTests.test_echo'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ThreadedTests.test_protocol_sslv23'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ThreadedTests.test_protocol_sslv3'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ThreadedTests.test_protocol_tlsv1'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.ThreadedTests.test_protocol_tlsv1_1'</span><span class="s2">,</span>
            <span class="s0"># Similar, they fail without monkey-patching.</span>
            <span class="s3">'test_ssl.TestPostHandshakeAuth.test_pha_no_pha_client'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.TestPostHandshakeAuth.test_pha_optional'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.TestPostHandshakeAuth.test_pha_required'</span><span class="s2">,</span>

            <span class="s0"># This gets None instead of http1.1, even without gevent</span>
            <span class="s3">'test_ssl.ThreadedTests.test_npn_protocols'</span><span class="s2">,</span>

            <span class="s0"># This fails to decode a filename even without gevent,</span>
            <span class="s0"># at least on High Sierra. Newer versions of the tests actually skip this.</span>
            <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_undecodable_filename'</span><span class="s2">,</span>
        <span class="s1">]</span>

    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This seems to be a buffering issue? Something isn't</span>
        <span class="s0"># getting flushed. (The output is wrong). Under PyPy3 5.7,</span>
        <span class="s0"># I couldn't reproduce locally in Ubuntu 16 in a VM</span>
        <span class="s0"># or a laptop with OS X. Under 5.8.0, I can reproduce it, but only</span>
        <span class="s0"># when run by the testrunner, not when run manually on the command line,</span>
        <span class="s0"># so something is changing in stdout buffering in those situations.</span>
        <span class="s3">'test_threading.ThreadJoinOnShutdown.test_2_join_in_forked_process'</span><span class="s2">,</span>
        <span class="s3">'test_threading.ThreadJoinOnShutdown.test_1_join_in_forked_process'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">TRAVIS:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># Likewise, but I haven't produced it locally.</span>
            <span class="s3">'test_threading.ThreadJoinOnShutdown.test_1_join_on_shutdown'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PYPY:</span>

    <span class="s1">wrapped_tests.update({</span>
        <span class="s0"># XXX: gevent: The error that was raised by that last call</span>
        <span class="s0"># left a socket open on the server or client. The server gets</span>
        <span class="s0"># to http/server.py(390)handle_one_request and blocks on</span>
        <span class="s0"># self.rfile.readline which apparently is where the SSL</span>
        <span class="s0"># handshake is done. That results in the exception being</span>
        <span class="s0"># raised on the client above, but apparently *not* on the</span>
        <span class="s0"># server. Consequently it sits trying to read from that</span>
        <span class="s0"># socket. On CPython, when the client socket goes out of scope</span>
        <span class="s0"># it is closed and the server raises an exception, closing the</span>
        <span class="s0"># socket. On PyPy, we need a GC cycle for that to happen.</span>
        <span class="s0"># Without the socket being closed and exception being raised,</span>
        <span class="s0"># the server cannot be stopped (it runs each request in the</span>
        <span class="s0"># same thread that would notice it had been stopped), and so</span>
        <span class="s0"># the cleanup method added by start_https_server to stop the</span>
        <span class="s0"># server blocks &quot;forever&quot;.</span>

        <span class="s0"># This is an important test, so rather than skip it in patched_tests_setup,</span>
        <span class="s0"># we do the gc before we return.</span>
        <span class="s3">'test_urllib2_localnet.TestUrlopen.test_https_with_cafile'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>

        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_command'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_handler'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_head_keep_alive'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_head_via_send_error'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_header_close'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_internal_key_error'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_request_line_trimming'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_return_custom_status'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_return_header_keep_alive'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_send_blank'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_send_error'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_bogus'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_digits'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_invalid'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_none'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_version_none_get'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.BaseHTTPServerTestCase.test_get'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_get'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_head'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_invalid_requests'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.SimpleHTTPServerTestCase.test_path_without_leading_slash'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.CGIHTTPServerTestCase.test_invaliduri'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httpservers.CGIHTTPServerTestCase.test_issue19435'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>

        <span class="s3">'test_httplib.TunnelTests.test_connect'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_httplib.SourceAddressTest.testHTTPConnectionSourceAddress'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>

        <span class="s0"># Unclear</span>
        <span class="s3">'test_urllib2_localnet.ProxyAuthTests.test_proxy_with_bad_password_raises_httperror'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
        <span class="s3">'test_urllib2_localnet.ProxyAuthTests.test_proxy_with_no_password_raises_httperror'</span><span class="s1">: _gc_at_end</span><span class="s2">,</span>
    <span class="s1">})</span>


<span class="s2">if </span><span class="s1">PY35:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_threadsafe_wait'</span><span class="s2">,</span>
        <span class="s0"># XXX: It seems that threading.Timer is not being greened properly, possibly</span>
        <span class="s0"># due to a similar issue to what gevent.threading documents for normal threads.</span>
        <span class="s0"># In any event, this test hangs forever</span>


        <span class="s3">'test_subprocess.POSIXProcessTestCase.test_preexec_errpipe_does_not_double_close_pipes'</span><span class="s2">,</span>
        <span class="s0"># Subclasses Popen, and overrides _execute_child. Expects things to be done</span>
        <span class="s0"># in a particular order in an exception case, but we don't follow that</span>
        <span class="s0"># exact order</span>


        <span class="s3">'test_selectors.PollSelectorTestCase.test_above_fd_setsize'</span><span class="s2">,</span>
        <span class="s0"># This test attempts to open many many file descriptors and</span>
        <span class="s0"># poll on them, expecting them all to be ready at once. But</span>
        <span class="s0"># libev limits the number of events it will return at once. Specifically,</span>
        <span class="s0"># on linux with epoll, it returns a max of 64 (ev_epoll.c).</span>

        <span class="s0"># XXX: Hangs (Linux only)</span>
        <span class="s3">'test_socket.NonBlockingTCPTests.testInitNonBlocking'</span><span class="s2">,</span>
        <span class="s0"># We don't handle the Linux-only SOCK_NONBLOCK option</span>
        <span class="s3">'test_socket.NonblockConstantTest.test_SOCK_NONBLOCK'</span><span class="s2">,</span>

        <span class="s0"># Tries to use multiprocessing which doesn't quite work in</span>
        <span class="s0"># monkey_test module (Windows only)</span>
        <span class="s3">'test_socket.TestSocketSharing.testShare'</span><span class="s2">,</span>

        <span class="s0"># Windows-only: Sockets have a 'ioctl' method in Python 3</span>
        <span class="s0"># implemented in the C code. This test tries to check</span>
        <span class="s0"># for the presence of the method in the class, which we don't</span>
        <span class="s0"># have because we don't inherit the C implementation. But</span>
        <span class="s0"># it should be found at runtime.</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_sock_ioctl'</span><span class="s2">,</span>

        <span class="s0"># XXX This fails for an unknown reason</span>
        <span class="s3">'test_httplib.HeaderTests.test_parse_all_octets'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">OSX:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># These raise &quot;OSError: 12 Cannot allocate memory&quot; on both</span>
            <span class="s0"># patched and unpatched runs</span>
            <span class="s3">'test_socket.RecvmsgSCMRightsStreamTest.testFDPassEmpty'</span><span class="s2">,</span>
        <span class="s1">]</span>

        <span class="s2">if </span><span class="s1">TRAVIS:</span>
            <span class="s0"># This has been seen to produce &quot;Inconsistency detected by</span>
            <span class="s0"># ld.so: dl-open.c: 231: dl_open_worker: Assertion</span>
            <span class="s0"># `_dl_debug_initialize (0, args-&gt;nsid)-&gt;r_state ==</span>
            <span class="s0"># RT_CONSISTENT' failed!&quot; and fail.</span>
            <span class="s1">disabled_tests += [</span>
                <span class="s3">'test_threading.ThreadTests.test_is_alive_after_fork'</span><span class="s2">,</span>
                <span class="s0"># This has timing constraints that are strict and do not always</span>
                <span class="s0"># hold.</span>
                <span class="s3">'test_selectors.PollSelectorTestCase.test_timeout'</span><span class="s2">,</span>
            <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">TRAVIS:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s3">'test_subprocess.ProcessTestCase.test_double_close_on_error'</span><span class="s2">,</span>
            <span class="s0"># This test is racy or OS-dependent. It passes locally (sufficiently fast machine)</span>
            <span class="s0"># but fails under Travis</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY35:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># XXX: Hangs</span>
        <span class="s3">'test_ssl.ThreadedTests.test_nonblocking_send'</span><span class="s2">,</span>
        <span class="s3">'test_ssl.ThreadedTests.test_socketserver'</span><span class="s2">,</span>
        <span class="s0"># Uses direct sendfile, doesn't properly check for it being enabled</span>
        <span class="s3">'test_socket.GeneralModuleTests.test__sendfile_use_sendfile'</span><span class="s2">,</span>


        <span class="s0"># Relies on the regex of the repr having the locked state (TODO: it'd be nice if</span>
        <span class="s0"># we did that).</span>
        <span class="s0"># XXX: These are commented out in the source code of test_threading because</span>
        <span class="s0"># this doesn't work.</span>
        <span class="s0"># 'lock_tests.LockTests.lest_locked_repr',</span>
        <span class="s0"># 'lock_tests.LockTests.lest_repr',</span>


        <span class="s0"># This test opens a socket, creates a new socket with the same fileno,</span>
        <span class="s0"># closes the original socket (and hence fileno) and then</span>
        <span class="s0"># expects that the calling setblocking() on the duplicate socket</span>
        <span class="s0"># will raise an error. Our implementation doesn't work that way because</span>
        <span class="s0"># setblocking() doesn't actually touch the file descriptor.</span>
        <span class="s0"># That's probably OK because this was a GIL state error in CPython</span>
        <span class="s0"># see https://github.com/python/cpython/commit/fa22b29960b4e683f4e5d7e308f674df2620473c</span>
        <span class="s3">'test_socket.TestExceptions.test_setblocking_invalidfd'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">sys.version_info[:</span><span class="s5">2</span><span class="s1">] == (</span><span class="s5">3</span><span class="s2">, </span><span class="s5">5</span><span class="s1">):</span>
        <span class="s0"># These tests are broken now that certificates are</span>
        <span class="s0"># expired and Python 3.5 is out of maintenance.</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s3">'test_ssl.ThreadedTests.test_crl_check'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.BasicSocketTests.test_parse_cert'</span><span class="s2">,</span>
        <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">ARES:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># These raise different errors or can't resolve</span>
            <span class="s0"># the IP address correctly</span>
            <span class="s3">'test_socket.GeneralModuleTests.test_host_resolution'</span><span class="s2">,</span>
            <span class="s3">'test_socket.GeneralModuleTests.test_getnameinfo'</span><span class="s2">,</span>
        <span class="s1">]</span>

        <span class="s2">if </span><span class="s1">sys.version_info[</span><span class="s5">1</span><span class="s1">] == </span><span class="s5">5</span><span class="s1">:</span>
            <span class="s1">disabled_tests += [</span>
                <span class="s0"># This test tends to time out, but only under 3.5, not under</span>
                <span class="s0"># 3.6 or 3.7. Seen with both libev and libuv</span>
                <span class="s3">'test_socket.SendfileUsingSendTest.testWithTimeoutTriggeredSend'</span><span class="s2">,</span>
            <span class="s1">]</span>

<span class="s2">if </span><span class="s1">sys.version_info[:</span><span class="s5">3</span><span class="s1">] &lt;= (</span><span class="s5">3</span><span class="s2">, </span><span class="s5">5</span><span class="s2">, </span><span class="s5">1</span><span class="s1">):</span>
    <span class="s0"># Python issue 26499 was fixed in 3.5.2 and these tests were added.</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s3">'test_httplib.BasicTest.test_mixed_reads'</span><span class="s2">,</span>
        <span class="s3">'test_httplib.BasicTest.test_read1_bound_content_length'</span><span class="s2">,</span>
        <span class="s3">'test_httplib.BasicTest.test_read1_content_length'</span><span class="s2">,</span>
        <span class="s3">'test_httplib.BasicTest.test_readline_bound_content_length'</span><span class="s2">,</span>
        <span class="s3">'test_httplib.BasicTest.test_readlines_content_length'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY36:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s3">'test_threading.MiscTestCase.test__all__'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s0"># We don't actually implement socket._sendfile_use_sendfile,</span>
    <span class="s0"># so these tests, which think they're using that and os.sendfile,</span>
    <span class="s0"># fail.</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.testCount'</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.testCountSmall'</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.testCountWithOffset'</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.testOffset'</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.testRegularFile'</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.testWithTimeout'</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.testEmptyFileSend'</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.testNonBlocking'</span><span class="s2">,</span>
        <span class="s3">'test_socket.SendfileUsingSendfileTest.test_errors'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s0"># Ditto</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s3">'test_socket.GeneralModuleTests.test__sendfile_use_sendfile'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This test requires Linux &gt;= 4.3. When we were running 'dist:</span>
        <span class="s0"># trusty' on the 4.4 kernel, it passed (~July 2017). But when</span>
        <span class="s0"># trusty became the default dist in September 2017 and updated</span>
        <span class="s0"># the kernel to 4.11.6, it begain failing. It fails on `res =</span>
        <span class="s0"># op.recv(assoclen + len(plain) + taglen)` (where 'op' is the</span>
        <span class="s0"># client socket) with 'OSError: [Errno 22] Invalid argument'</span>
        <span class="s0"># for unknown reasons. This is *after* having successfully</span>
        <span class="s0"># called `op.sendmsg_afalg`. Post 3.6.0, what we test with,</span>
        <span class="s0"># the test was changed to require Linux 4.9 and the data was changed,</span>
        <span class="s0"># so this is not our fault. We should eventually update this when we</span>
        <span class="s0"># update our 3.6 version.</span>
        <span class="s0"># See https://bugs.python.org/issue29324</span>
        <span class="s3">'test_socket.LinuxKernelCryptoAPI.test_aead_aes_gcm'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY37:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># These want to use the private '_communicate' method, which</span>
        <span class="s0"># our Popen doesn't have.</span>
        <span class="s3">'test_subprocess.MiscTests.test_call_keyboardinterrupt_no_kill'</span><span class="s2">,</span>
        <span class="s3">'test_subprocess.MiscTests.test_context_manager_keyboardinterrupt_no_kill'</span><span class="s2">,</span>
        <span class="s3">'test_subprocess.MiscTests.test_run_keyboardinterrupt_no_kill'</span><span class="s2">,</span>

        <span class="s0"># This wants to check that the underlying fileno is blocking,</span>
        <span class="s0"># but it isn't.</span>
        <span class="s3">'test_socket.NonBlockingTCPTests.testSetBlocking'</span><span class="s2">,</span>

        <span class="s0"># 3.7b2 made it impossible to instantiate SSLSocket objects</span>
        <span class="s0"># directly, and this tests for that, but we don't follow that change.</span>
        <span class="s3">'test_ssl.BasicSocketTests.test_private_init'</span><span class="s2">,</span>

        <span class="s0"># 3.7b2 made a change to this test that on the surface looks incorrect,</span>
        <span class="s0"># but it passes when they run it and fails when we do. It's not</span>
        <span class="s0"># clear why.</span>
        <span class="s3">'test_ssl.ThreadedTests.test_check_hostname_idn'</span><span class="s2">,</span>

        <span class="s0"># These appear to hang, haven't investigated why</span>
        <span class="s3">'test_ssl.SimpleBackgroundTests.test_get_server_certificate'</span><span class="s2">,</span>
        <span class="s0"># Probably the same as NetworkConnectionNoServer.test_create_connection_timeout</span>
        <span class="s3">'test_socket.NetworkConnectionNoServer.test_create_connection'</span><span class="s2">,</span>

        <span class="s0"># Internals of the threading module that change.</span>
        <span class="s3">'test_threading.ThreadTests.test_finalization_shutdown'</span><span class="s2">,</span>
        <span class="s3">'test_threading.ThreadTests.test_shutdown_locks'</span><span class="s2">,</span>
        <span class="s0"># Expects a deprecation warning we don't raise</span>
        <span class="s3">'test_threading.ThreadTests.test_old_threading_api'</span><span class="s2">,</span>
        <span class="s0"># This tries to use threading.interrupt_main() from a new Thread;</span>
        <span class="s0"># but of course that's actually the same thread and things don't</span>
        <span class="s0"># work as expected.</span>
        <span class="s3">'test_threading.InterruptMainTests.test_interrupt_main_subthread'</span><span class="s2">,</span>
        <span class="s3">'test_threading.InterruptMainTests.test_interrupt_main_noerror'</span><span class="s2">,</span>

        <span class="s0"># TLS1.3 seems flaky</span>
        <span class="s3">'test_ssl.ThreadedTests.test_wrong_cert_tls13'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">sys.version_info &lt; (</span><span class="s5">3</span><span class="s2">, </span><span class="s5">7</span><span class="s2">, </span><span class="s5">6</span><span class="s1">):</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># Earlier versions parse differently so the newer test breaks</span>
            <span class="s3">'test_ssl.BasicSocketTests.test_parse_all_sans'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.BasicSocketTests.test_parse_cert_CVE_2013_4238'</span><span class="s2">,</span>
        <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">APPVEYOR:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># This sometimes produces ``self.assertEqual(1, len(s.select(0))): 1 != 0``.</span>
            <span class="s0"># Probably needs to spin the loop once.</span>
            <span class="s3">'test_selectors.BaseSelectorTestCase.test_timeout'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY38:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This one seems very strict: doesn't want a pathlike</span>
        <span class="s0"># first argument when shell is true.</span>
        <span class="s3">'test_subprocess.RunFuncTestCase.test_run_with_pathlike_path'</span><span class="s2">,</span>
        <span class="s0"># This tests for a warning we don't raise.</span>
        <span class="s3">'test_subprocess.RunFuncTestCase.test_bufsize_equal_one_binary_mode'</span><span class="s2">,</span>

        <span class="s0"># This compares the output of threading.excepthook with</span>
        <span class="s0"># data constructed in Python. But excepthook is implemented in C</span>
        <span class="s0"># and can't see the patched threading.get_ident() we use, so the</span>
        <span class="s0"># output doesn't match.</span>
        <span class="s3">'test_threading.ExceptHookTests.test_excepthook_thread_None'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">sys.version_info[:</span><span class="s5">3</span><span class="s1">] &lt; (</span><span class="s5">3</span><span class="s2">, </span><span class="s5">8</span><span class="s2">, </span><span class="s5">1</span><span class="s1">):</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># Earlier versions parse differently so the newer test breaks</span>
            <span class="s3">'test_ssl.BasicSocketTests.test_parse_all_sans'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.BasicSocketTests.test_parse_cert_CVE_2013_4238'</span><span class="s2">,</span>
        <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">sys.version_info[:</span><span class="s5">3</span><span class="s1">] &lt; (</span><span class="s5">3</span><span class="s2">, </span><span class="s5">8</span><span class="s2">, </span><span class="s5">10</span><span class="s1">):</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># These were added for fixes sometime between 3.8.1 and 3.8.10</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_makepasv_issue43285_security_disabled'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_makepasv_issue43285_security_enabled_default'</span><span class="s2">,</span>
            <span class="s3">'test_httplib.BasicTest.test_dir_with_added_behavior_on_status'</span><span class="s2">,</span>
            <span class="s3">'test_httplib.TunnelTests.test_tunnel_connect_single_send_connection_setup'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.TestSSLDebug.test_msg_callback_deadlock_bpo43577'</span><span class="s2">,</span>
            <span class="s0"># This one fails with the updated certs</span>
            <span class="s3">'test_ssl.ContextTests.test_load_verify_cadata'</span><span class="s2">,</span>
            <span class="s0"># This one times out on 3.7.1 on Appveyor</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClassMixin.test_retrbinary_rest'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">RESOLVER_DNSPYTHON:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This does two things DNS python doesn't. First, it sends it</span>
        <span class="s0"># capital letters and expects them to be returned lowercase.</span>
        <span class="s0"># Second, it expects the symbolic scopeid to be stripped from the end.</span>
        <span class="s3">'test_socket.GeneralModuleTests.test_getaddrinfo_ipv6_scopeid_symbolic'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s0"># if 'signalfd' in os.environ.get('GEVENT_BACKEND', ''):</span>
<span class="s0">#     # tests that don't interact well with signalfd</span>
<span class="s0">#     disabled_tests.extend([</span>
<span class="s0">#         'test_signal.SiginterruptTest.test_siginterrupt_off',</span>
<span class="s0">#         'test_socketserver.SocketServerTest.test_ForkingTCPServer',</span>
<span class="s0">#         'test_socketserver.SocketServerTest.test_ForkingUDPServer',</span>
<span class="s0">#         'test_socketserver.SocketServerTest.test_ForkingUnixStreamServer'])</span>

<span class="s0"># LibreSSL reports OPENSSL_VERSION_INFO (2, 0, 0, 0, 0) regardless of its version,</span>
<span class="s0"># so this is known to fail on some distros. We don't want to detect this because we</span>
<span class="s0"># don't want to trigger the side-effects of importing ssl prematurely if we will</span>
<span class="s0"># be monkey-patching, so we skip this test everywhere. It doesn't do much for us</span>
<span class="s0"># anyway.</span>
<span class="s1">disabled_tests += [</span>
    <span class="s3">'test_ssl.BasicSocketTests.test_openssl_version'</span>
<span class="s1">]</span>

<span class="s2">if </span><span class="s1">OSX:</span>

    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This sometimes produces OSError: Errno 40: Message too long</span>
        <span class="s3">'test_socket.RecvmsgIntoTCPTest.testRecvmsgIntoGenerator'</span><span class="s2">,</span>

        <span class="s0"># These sometime timeout. Cannot reproduce locally.</span>
        <span class="s3">'test_ftp.TestTLS_FTPClassMixin.test_mlsd'</span><span class="s2">,</span>
        <span class="s3">'test_ftp.TestTLS_FTPClassMixin.test_retrlines_too_long'</span><span class="s2">,</span>
        <span class="s3">'test_ftp.TestTLS_FTPClassMixin.test_storlines'</span><span class="s2">,</span>
        <span class="s3">'test_ftp.TestTLS_FTPClassMixin.test_retrbinary_rest'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">RESOLVER_ARES </span><span class="s2">and </span><span class="s1">PY38 </span><span class="s2">and not </span><span class="s1">RUNNING_ON_CI:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># When updating to 1.16.0 this was seen locally, but not on CI.</span>
            <span class="s0"># Tuples differ: ('ff02::1de:c0:face:8d', 1234, 0, 0)</span>
            <span class="s0">#             != ('ff02::1de:c0:face:8d', 1234, 0, 1)</span>
            <span class="s3">'test_socket.GeneralModuleTests.test_getaddrinfo_ipv6_scopeid_symbolic'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY39:</span>

    <span class="s1">disabled_tests += [</span>
        <span class="s0"># Depends on exact details of the repr. Eww.</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_repr'</span><span class="s2">,</span>
        <span class="s0"># Tries to wait for the process without using Popen APIs, and expects the</span>
        <span class="s0"># ``returncode`` attribute to stay None. But we have already hooked SIGCHLD, so</span>
        <span class="s0"># we see and set the ``returncode``; there is no way to wait that doesn't do that.</span>
        <span class="s3">'test_subprocess.POSIXProcessTestTest.test_send_signal_race'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">sys.version_info[:</span><span class="s5">3</span><span class="s1">] &lt; (</span><span class="s5">3</span><span class="s2">, </span><span class="s5">9</span><span class="s2">, </span><span class="s5">5</span><span class="s1">):</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># These were added for fixes sometime between 3.9.1 and 3.9.5</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_makepasv_issue43285_security_disabled'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestFTPClass.test_makepasv_issue43285_security_enabled_default'</span><span class="s2">,</span>
            <span class="s3">'test_httplib.BasicTest.test_dir_with_added_behavior_on_status'</span><span class="s2">,</span>
            <span class="s3">'test_httplib.TunnelTests.test_tunnel_connect_single_send_connection_setup'</span><span class="s2">,</span>
            <span class="s3">'test_ssl.TestSSLDebug.test_msg_callback_deadlock_bpo43577'</span><span class="s2">,</span>
            <span class="s0"># This one fails with the updated certs</span>
            <span class="s3">'test_ssl.ContextTests.test_load_verify_cadata'</span><span class="s2">,</span>
            <span class="s0"># These time out on 3.9.1 on Appveyor</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClassMixin.test_retrbinary_rest'</span><span class="s2">,</span>
            <span class="s3">'test_ftplib.TestTLS_FTPClassMixin.test_retrlines_too_long'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY310:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># They arbitrarily made some types so that they can't be created;</span>
        <span class="s0"># that's an implementation detail we're not going to follow (</span>
        <span class="s0"># it would require them to be factory functions).</span>
        <span class="s3">'test_select.SelectTestCase.test_disallow_instantiation'</span><span class="s2">,</span>
        <span class="s3">'test_threading.ThreadTests.test_disallow_instantiation'</span><span class="s2">,</span>
        <span class="s0"># This wants two true threads to work, but a CPU bound loop</span>
        <span class="s0"># in a greenlet can't be interrupted.</span>
        <span class="s3">'test_threading.InterruptMainTests.test_can_interrupt_tight_loops'</span><span class="s2">,</span>
        <span class="s0"># We don't currently implement pipesize.</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_pipesize_default'</span><span class="s2">,</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test_pipesizes'</span><span class="s2">,</span>
        <span class="s0"># Unknown</span>
        <span class="s3">'test_signal.SiginterruptTest.test_siginterrupt_off'</span><span class="s2">,</span>
    <span class="s1">]</span>

    <span class="s2">if </span><span class="s1">TRAVIS:</span>
        <span class="s1">disabled_tests += [</span>
            <span class="s0"># The mixing of subinterpreters (with threads) and gevent apparently</span>
            <span class="s0"># leads to a segfault on Ubuntu/GitHubActions/3.10rc1. Not clear why.</span>
            <span class="s0"># But that's not a great use case for gevent.</span>
            <span class="s3">'test_threading.SubinterpThreadingTests.test_threads_join'</span><span class="s2">,</span>
            <span class="s3">'test_threading.SubinterpThreadingTests.test_threads_join_2'</span><span class="s2">,</span>
        <span class="s1">]</span>

<span class="s2">if </span><span class="s1">PY311:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># CPython issue #27718: This wants to require all objects to</span>
        <span class="s0"># have a __module__ of 'signal' because pydoc. Obviously our patches don't.</span>
        <span class="s3">'test_signal.GenericTests.test_functions_module_attr'</span><span class="s2">,</span>
        <span class="s0"># 3.11 added subprocess._USE_VFORK and subprocess._USE_POSIX_SPAWN.</span>
        <span class="s0"># We don't support either of those (although USE_VFORK might be possible?)</span>
        <span class="s3">'test_subprocess.ProcessTestCase.test__use_vfork'</span><span class="s2">,</span>
    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">TRAVIS:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># These tests frequently break when we try to use newer Travis CI images,</span>
        <span class="s0"># due to different versions of OpenSSL being available. See above for some</span>
        <span class="s0"># specific examples. Usually the tests catch up, eventually (e.g., at this writing,</span>
        <span class="s0"># the 3.9b1 tests are fine on Ubuntu Bionic, but all other versions fail).</span>
        <span class="s3">'test_ssl.ContextTests.test_options'</span><span class="s2">,</span>
        <span class="s3">'test_ssl.ThreadedTests.test_alpn_protocols'</span><span class="s2">,</span>
        <span class="s3">'test_ssl.ThreadedTests.test_default_ecdh_curve'</span><span class="s2">,</span>
        <span class="s3">'test_ssl.ThreadedTests.test_shared_ciphers'</span><span class="s2">,</span>

    <span class="s1">]</span>

<span class="s2">if </span><span class="s1">RUNNING_ON_MUSLLINUX:</span>
    <span class="s1">disabled_tests += [</span>
        <span class="s0"># This is supposed to *not* crash, but on the muslilnux image, it</span>
        <span class="s0"># does crash.</span>
        <span class="s3">'test_threading.ThreadingExceptionTests.test_recursion_limit'</span><span class="s2">,</span>
    <span class="s1">]</span>


<span class="s0"># Now build up the data structure we'll use to actually find disabled tests</span>
<span class="s0"># to avoid a linear scan for every file (it seems the list could get quite large)</span>
<span class="s0"># (First, freeze the source list to make sure it isn't modified anywhere)</span>

<span class="s2">def </span><span class="s1">_build_test_structure(sequence_of_tests):</span>

    <span class="s1">_disabled_tests = frozenset(sequence_of_tests)</span>

    <span class="s1">disabled_tests_by_file = collections.defaultdict(set)</span>
    <span class="s2">for </span><span class="s1">file_case_meth </span><span class="s2">in </span><span class="s1">_disabled_tests:</span>
        <span class="s1">file_name</span><span class="s2">, </span><span class="s1">_case</span><span class="s2">, </span><span class="s1">_meth = file_case_meth.split(</span><span class="s3">'.'</span><span class="s1">)</span>

        <span class="s1">by_file = disabled_tests_by_file[file_name]</span>

        <span class="s1">by_file.add(file_case_meth)</span>

    <span class="s2">return </span><span class="s1">disabled_tests_by_file</span>

<span class="s1">_disabled_tests_by_file = _build_test_structure(disabled_tests)</span>

<span class="s1">_wrapped_tests_by_file = _build_test_structure(wrapped_tests)</span>


<span class="s2">def </span><span class="s1">disable_tests_in_source(source</span><span class="s2">, </span><span class="s1">filename):</span>
    <span class="s0"># Source and filename are both native strings.</span>

    <span class="s2">if </span><span class="s1">filename.startswith(</span><span class="s3">'./'</span><span class="s1">):</span>
        <span class="s0"># turn &quot;./test_socket.py&quot; (used for auto-complete) into &quot;test_socket.py&quot;</span>
        <span class="s1">filename = filename[</span><span class="s5">2</span><span class="s1">:]</span>

    <span class="s2">if </span><span class="s1">filename.endswith(</span><span class="s3">'.py'</span><span class="s1">):</span>
        <span class="s1">filename = filename[:-</span><span class="s5">3</span><span class="s1">]</span>


    <span class="s0"># XXX ignoring TestCase class name (just using function name).</span>
    <span class="s0"># Maybe we should do this with the AST, or even after the test is</span>
    <span class="s0"># imported.</span>
    <span class="s1">my_disabled_tests = _disabled_tests_by_file.get(filename</span><span class="s2">, </span><span class="s1">())</span>
    <span class="s1">my_wrapped_tests = _wrapped_tests_by_file.get(filename</span><span class="s2">, </span><span class="s1">{})</span>


    <span class="s2">if </span><span class="s1">my_disabled_tests </span><span class="s2">or </span><span class="s1">my_wrapped_tests:</span>
        <span class="s0"># Insert our imports early in the file.</span>
        <span class="s0"># If we do it on a def-by-def basis, we can break syntax</span>
        <span class="s0"># if the function is already decorated</span>
        <span class="s1">pattern = </span><span class="s3">r'^import .*'</span>
        <span class="s1">replacement = </span><span class="s3">r'from gevent.testing import patched_tests_setup as _GEVENT_PTS;'</span>
        <span class="s1">replacement += </span><span class="s3">r'import unittest as _GEVENT_UTS;'</span>
        <span class="s1">replacement += </span><span class="s3">r'\g&lt;0&gt;'</span>
        <span class="s1">source</span><span class="s2">, </span><span class="s1">n = re.subn(pattern</span><span class="s2">, </span><span class="s1">replacement</span><span class="s2">, </span><span class="s1">source</span><span class="s2">, </span><span class="s5">1</span><span class="s2">, </span><span class="s1">re.MULTILINE)</span>

        <span class="s1">print(</span><span class="s3">&quot;Added imports&quot;</span><span class="s2">, </span><span class="s1">n)</span>

    <span class="s0"># Test cases will always be indented some,</span>
    <span class="s0"># so use [ \t]+. Without indentation, test_main, commonly used as the</span>
    <span class="s0"># __main__ function at the top level, could get matched. \s matches</span>
    <span class="s0"># newlines even in MULTILINE mode so it would still match that.</span>
    <span class="s1">my_disabled_testcases = set()</span>
    <span class="s2">for </span><span class="s1">test </span><span class="s2">in </span><span class="s1">my_disabled_tests:</span>
        <span class="s1">testcase = test.split(</span><span class="s3">'.'</span><span class="s1">)[-</span><span class="s5">1</span><span class="s1">]</span>
        <span class="s1">my_disabled_testcases.add(testcase)</span>
        <span class="s0"># def foo_bar(self)</span>
        <span class="s0"># -&gt;</span>
        <span class="s0"># @_GEVENT_UTS.skip('Removed by patched_tests_setup')</span>
        <span class="s0"># def foo_bar(self)</span>
        <span class="s1">pattern = </span><span class="s3">r&quot;^([ \t]+)def &quot; </span><span class="s1">+ testcase</span>
        <span class="s1">replacement = </span><span class="s3">r&quot;\1@_GEVENT_UTS.skip('Removed by patched_tests_setup: %s')\n&quot; </span><span class="s1">% (test</span><span class="s2">,</span><span class="s1">)</span>
        <span class="s1">replacement += </span><span class="s3">r&quot;\g&lt;0&gt;&quot;</span>
        <span class="s1">source</span><span class="s2">, </span><span class="s1">n = re.subn(pattern</span><span class="s2">, </span><span class="s1">replacement</span><span class="s2">, </span><span class="s1">source</span><span class="s2">, </span><span class="s5">0</span><span class="s2">, </span><span class="s1">re.MULTILINE)</span>
        <span class="s1">print(</span><span class="s3">'Skipped %s (%d)' </span><span class="s1">% (testcase</span><span class="s2">, </span><span class="s1">n)</span><span class="s2">, </span><span class="s1">file=sys.stderr)</span>


    <span class="s2">for </span><span class="s1">test </span><span class="s2">in </span><span class="s1">my_wrapped_tests:</span>
        <span class="s1">testcase = test.split(</span><span class="s3">'.'</span><span class="s1">)[-</span><span class="s5">1</span><span class="s1">]</span>
        <span class="s2">if </span><span class="s1">testcase </span><span class="s2">in </span><span class="s1">my_disabled_testcases:</span>
            <span class="s1">print(</span><span class="s3">&quot;Not wrapping %s because it is skipped&quot; </span><span class="s1">% (test</span><span class="s2">,</span><span class="s1">))</span>
            <span class="s2">continue</span>

        <span class="s0"># def foo_bar(self)</span>
        <span class="s0"># -&gt;</span>
        <span class="s0"># @_GEVENT_PTS._PatchedTest('file.Case.name')</span>
        <span class="s0"># def foo_bar(self)</span>
        <span class="s1">pattern = </span><span class="s3">r&quot;^([ \t]+)def &quot; </span><span class="s1">+ testcase</span>
        <span class="s1">replacement = </span><span class="s3">r&quot;\1@_GEVENT_PTS._PatchedTest('%s')\n&quot; </span><span class="s1">% (test</span><span class="s2">,</span><span class="s1">)</span>
        <span class="s1">replacement += </span><span class="s3">r&quot;\g&lt;0&gt;&quot;</span>

        <span class="s1">source</span><span class="s2">, </span><span class="s1">n = re.subn(pattern</span><span class="s2">, </span><span class="s1">replacement</span><span class="s2">, </span><span class="s1">source</span><span class="s2">, </span><span class="s5">0</span><span class="s2">, </span><span class="s1">re.MULTILINE)</span>
        <span class="s1">print(</span><span class="s3">'Wrapped %s (%d)' </span><span class="s1">% (testcase</span><span class="s2">, </span><span class="s1">n)</span><span class="s2">, </span><span class="s1">file=sys.stderr)</span>

    <span class="s2">return </span><span class="s1">source</span>
</pre>
</body>
</html>